# Form implementation generated from reading ui file 'interface\found_title.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FoundTitle(object):
    def setupUi(self, FoundTitle):
        FoundTitle.setObjectName("FoundTitle")
        FoundTitle.resize(186, 52)
        FoundTitle.setStyleSheet(
            "* {border: none;color: rgb(255,255,255)}\n"
            "#FoundTitle {background-color: rgb(30,30,30)}\n"
            "#FoundTitle * {background-color: transparent}\n"
            "#FoundTitle:hover {background-color: rgb(48,48,48)}\n"
            "#titleIcon {background-color: rgb(37,37,37);border-radius: 20px}"
        )
        self.foundTitleLayout = QtWidgets.QHBoxLayout(FoundTitle)
        self.foundTitleLayout.setContentsMargins(20, 6, 20, 6)
        self.foundTitleLayout.setSpacing(15)
        self.foundTitleLayout.setObjectName("foundTitleLayout")
        self.titleIcon = QtWidgets.QLabel(parent=FoundTitle)
        self.titleIcon.setMinimumSize(QtCore.QSize(40, 40))
        self.titleIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.titleIcon.setObjectName("titleIcon")
        self.foundTitleLayout.addWidget(self.titleIcon)
        self.titleLabel = QtWidgets.QLabel(parent=FoundTitle)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.foundTitleLayout.addWidget(self.titleLabel)

        self.retranslateUi(FoundTitle)
        QtCore.QMetaObject.connectSlotsByName(FoundTitle)

    def retranslateUi(self, FoundTitle):
        pass
