# Form implementation generated from reading ui file 'interface\player_controls.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlayerControls(object):
    def setupUi(self, PlayerControls):
        PlayerControls.setObjectName("PlayerControls")
        PlayerControls.resize(979, 224)
        PlayerControls.setMinimumSize(QtCore.QSize(0, 224))
        PlayerControls.setMaximumSize(QtCore.QSize(16777215, 224))
        PlayerControls.setStyleSheet(
            "#PlayerControls {\n"
            "    background-color: qlineargradient(\n"
            "        spread:pad, \n"
            "        x1:0.5, y1:1, x2:0.5, y2:0, \n"
            "        stop:0 rgba(0, 0, 0, 158), stop:1 rgba(255, 255, 255, 0)\n"
            "    );\n"
            "}\n"
            "QFrame * {\n"
            "    background-color: transparent;\n"
            "    border: none;\n"
            "    color: white;\n"
            "}\n"
            "QPushButton {\n"
            "    padding-left: 0.5px;\n"
            "    border-radius: 25px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: rgba(110,110,110,50);\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    background-color: rgba(180,180,180,50);\n"
            "}\n"
            "#playBtn {\n"
            "    border-radius: 40px;\n"
            "    padding-left: 2px;\n"
            "}\n"
            "\n"
            "/* SLIDER */\n"
            "QSlider {\n"
            "    background-color: transparent;\n"
            "    height: 20px;\n"
            "}\n"
            "QSlider::groove:horizontal {\n"
            "    background: transparent;\n"
            "}\n"
            "QSlider::sub-page:horizontal {\n"
            "    background: white;\n"
            "    margin-top:9px;\n"
            "    margin-bottom:9px;\n"
            "    height: 2px;\n"
            "}\n"
            "QSlider::add-page:horizontal {\n"
            "    background: rgba(180,180,180,50);\n"
            "    margin-top:9px;\n"
            "    margin-bottom:9px;\n"
            "    height: 2px;\n"
            "}\n"
            "QSlider::handle:horizontal {\n"
            "    background: white;\n"
            "    height: 14px;\n"
            "    width:14px;\n"
            "    margin-top:3px;\n"
            "    margin-bottom:3px;\n"
            "    border-radius: 7px;\n"
            "}\n"
            "QSlider::handle:horizontal:hover {\n"
            "    margin-top:1px;\n"
            "    margin-bottom:1px;\n"
            "    width: 18px;\n"
            "    border-radius: 9px;\n"
            "}\n"
            "QSlider::handle:horizontal:pressed {\n"
            "    margin: 0px;\n"
            "    width: 20px;\n"
            "    border-radius: 10px;\n"
            "}\n"
            "\n"
            "#playbackSlider::handle:horizontal,\n"
            "#playbackSlider::sub-page:horizontal {\n"
            "    background: rgb(179,33,33);\n"
            "}"
        )
        self.playerControlsLayout = QtWidgets.QVBoxLayout(PlayerControls)
        self.playerControlsLayout.setContentsMargins(40, 10, 40, 40)
        self.playerControlsLayout.setSpacing(10)
        self.playerControlsLayout.setObjectName("playerControlsLayout")
        self.titleFrame = QtWidgets.QFrame(parent=PlayerControls)
        self.titleFrame.setObjectName("titleFrame")
        self.titleFrameLayout = QtWidgets.QVBoxLayout(self.titleFrame)
        self.titleFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.titleFrameLayout.setSpacing(5)
        self.titleFrameLayout.setObjectName("titleFrameLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.titleFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.titleFrameLayout.addWidget(self.titleLabel)
        self.episodeLabelLayout = QtWidgets.QHBoxLayout()
        self.episodeLabelLayout.setSpacing(0)
        self.episodeLabelLayout.setObjectName("episodeLabelLayout")
        self.episodeNumberLabel = QtWidgets.QLabel(parent=self.titleFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.episodeNumberLabel.sizePolicy().hasHeightForWidth()
        )
        self.episodeNumberLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.episodeNumberLabel.setFont(font)
        self.episodeNumberLabel.setObjectName("episodeNumberLabel")
        self.episodeLabelLayout.addWidget(self.episodeNumberLabel)
        self.playbackLabel = QtWidgets.QLabel(parent=self.titleFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.playbackLabel.sizePolicy().hasHeightForWidth()
        )
        self.playbackLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.playbackLabel.setFont(font)
        self.playbackLabel.setObjectName("playbackLabel")
        self.episodeLabelLayout.addWidget(self.playbackLabel)
        self.titleFrameLayout.addLayout(self.episodeLabelLayout)
        self.playerControlsLayout.addWidget(self.titleFrame)
        self.playbackSlider = QtWidgets.QSlider(parent=PlayerControls)
        self.playbackSlider.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.playbackSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.playbackSlider.setObjectName("playbackSlider")
        self.playerControlsLayout.addWidget(self.playbackSlider)
        self.controlsFrame = QtWidgets.QFrame(parent=PlayerControls)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.controlsFrame.sizePolicy().hasHeightForWidth()
        )
        self.controlsFrame.setSizePolicy(sizePolicy)
        self.controlsFrame.setObjectName("controlsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.controlsFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.homeBtn = QtWidgets.QPushButton(parent=self.controlsFrame)
        self.homeBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.homeBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.homeBtn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/base/home.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.homeBtn.setIcon(icon)
        self.homeBtn.setIconSize(QtCore.QSize(20, 20))
        self.homeBtn.setObjectName("homeBtn")
        self.horizontalLayout_4.addWidget(self.homeBtn)
        self.episodesBtn = QtWidgets.QPushButton(parent=self.controlsFrame)
        self.episodesBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.episodesBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.episodesBtn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/base/playlist.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.episodesBtn.setIcon(icon1)
        self.episodesBtn.setIconSize(QtCore.QSize(20, 20))
        self.episodesBtn.setObjectName("episodesBtn")
        self.horizontalLayout_4.addWidget(self.episodesBtn)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.playBtn = QtWidgets.QPushButton(parent=self.controlsFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playBtn.sizePolicy().hasHeightForWidth())
        self.playBtn.setSizePolicy(sizePolicy)
        self.playBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.playBtn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/base/play.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.playBtn.setIcon(icon2)
        self.playBtn.setIconSize(QtCore.QSize(30, 30))
        self.playBtn.setObjectName("playBtn")
        self.gridLayout.addWidget(self.playBtn, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_3.addItem(spacerItem1)
        self.volumeBtn = QtWidgets.QPushButton(parent=self.controlsFrame)
        self.volumeBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.volumeBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.volumeBtn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/base/volume_height.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.volumeBtn.setIcon(icon3)
        self.volumeBtn.setIconSize(QtCore.QSize(20, 20))
        self.volumeBtn.setObjectName("volumeBtn")
        self.horizontalLayout_3.addWidget(self.volumeBtn)
        self.volumeSlider = QtWidgets.QSlider(parent=self.controlsFrame)
        self.volumeSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.volumeSlider.setMaximumSize(QtCore.QSize(100, 16777215))
        self.volumeSlider.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.volumeSlider.setMaximum(10)
        self.volumeSlider.setSingleStep(1)
        self.volumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_3.addWidget(self.volumeSlider)
        self.resolutionBtn = QtWidgets.QPushButton(parent=self.controlsFrame)
        self.resolutionBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.resolutionBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.resolutionBtn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/base/resolution_sd.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.resolutionBtn.setIcon(icon4)
        self.resolutionBtn.setIconSize(QtCore.QSize(20, 20))
        self.resolutionBtn.setObjectName("resolutionBtn")
        self.horizontalLayout_3.addWidget(self.resolutionBtn)
        self.fullscreenBtn = QtWidgets.QPushButton(parent=self.controlsFrame)
        self.fullscreenBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.fullscreenBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.fullscreenBtn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/base/fullscreen.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.fullscreenBtn.setIcon(icon5)
        self.fullscreenBtn.setIconSize(QtCore.QSize(20, 20))
        self.fullscreenBtn.setObjectName("fullscreenBtn")
        self.horizontalLayout_3.addWidget(self.fullscreenBtn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.playerControlsLayout.addWidget(self.controlsFrame)

        self.retranslateUi(PlayerControls)
        QtCore.QMetaObject.connectSlotsByName(PlayerControls)

    def retranslateUi(self, PlayerControls):
        pass
