# Form implementation generated from reading ui file 'interface\main.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 640)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet(
            "QWidget {\n"
            "    color: rgb(255,255,255);\n"
            "}\n"
            "\n"
            "QFrame {\n"
            "    border: none;\n"
            "}\n"
            "\n"
            "/*  BUTTONS */\n"
            "QPushButton {\n"
            "    padding-left: 0.5px;\n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    border-radius: 5px;\n"
            "    border: none;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(20, 20, 20);\n"
            "    border-radius: 12px;\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(110,110,110);\n"
            "}\n"
            "\n"
            "\n"
            "/*  TOP FRAME */\n"
            "#topFrame {\n"
            "    background-color: rgb(0, 0, 0);\n"
            "}\n"
            "#logo {\n"
            "    color: rgb(158,158,148);\n"
            "}\n"
            "\n"
            "/* CENTRAL FRAME */\n"
            "#centralFrame {\n"
            "    background-color: rgb(18,18,18);\n"
            "}"
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topFrame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topFrame.sizePolicy().hasHeightForWidth())
        self.topFrame.setSizePolicy(sizePolicy)
        self.topFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.topFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout.setContentsMargins(15, 0, 7, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(parent=self.topFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.frame = QtWidgets.QFrame(parent=self.topFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeAppBtn = QtWidgets.QPushButton(parent=self.frame)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(25, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/base/line.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.minimizeAppBtn.setIcon(icon)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(10, 10))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeAppBtn = QtWidgets.QPushButton(parent=self.frame)
        self.maximizeAppBtn.setMinimumSize(QtCore.QSize(25, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/base/window.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.maximizeAppBtn.setIcon(icon1)
        self.maximizeAppBtn.setIconSize(QtCore.QSize(12, 12))
        self.maximizeAppBtn.setObjectName("maximizeAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(parent=self.frame)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(25, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/base/cross.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.closeAppBtn.setIcon(icon2)
        self.closeAppBtn.setIconSize(QtCore.QSize(10, 10))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.topFrame)
        self.centralFrame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralFrame.sizePolicy().hasHeightForWidth())
        self.centralFrame.setSizePolicy(sizePolicy)
        self.centralFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.centralFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.centralFrame.setObjectName("centralFrame")
        self.verticalLayout.addWidget(self.centralFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "AniTogether"))
