# Form implementation generated from reading ui file 'interface\title_from_history.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TitleFromHistory(object):
    def setupUi(self, TitleFromHistory):
        TitleFromHistory.setObjectName("TitleFromHistory")
        TitleFromHistory.resize(350, 500)
        TitleFromHistory.setStyleSheet(
            "#TitleFromHistory {\n"
            "    background-color:  rgb(37,37,37);\n"
            "    border-radius: 4px;\n"
            "}\n"
            "#TitleFromHistory * {background-color: transparent;color: white;}\n"
            "#watchProgressLabel {padding-left:10px;}\n"
            "/* SLIDER */\n"
            "QSlider {height: 20px}\n"
            "QSlider::handle:horizontal {width:0px}\n"
            "QSlider::groove:horizontal {background: rgba(179,33,33,50)}\n"
            "QSlider::sub-page:horizontal {\n"
            "    background: rgb(179,33,33);\n"
            "    border-bottom-left-radius: 3px;\n"
            "    margin-right:1px;\n"
            "}\n"
            "QSlider::add-page:horizontal {\n"
            "    background: rgba(179,33,33,50);\n"
            "    border-bottom-right-radius: 3px\n"
            "}\n"
            ""
        )
        self.watchProgressSlider = QtWidgets.QSlider(parent=TitleFromHistory)
        self.watchProgressSlider.setEnabled(False)
        self.watchProgressSlider.setGeometry(QtCore.QRect(30, 430, 84, 30))
        self.watchProgressSlider.setMinimumSize(QtCore.QSize(0, 30))
        self.watchProgressSlider.setMaximumSize(QtCore.QSize(16777215, 30))
        self.watchProgressSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.watchProgressSlider.setObjectName("watchProgressSlider")
        self.watchProgressLabel = QtWidgets.QLabel(parent=TitleFromHistory)
        self.watchProgressLabel.setGeometry(QtCore.QRect(40, 440, 49, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.watchProgressLabel.setFont(font)
        self.watchProgressLabel.setObjectName("watchProgressLabel")

        self.retranslateUi(TitleFromHistory)
        QtCore.QMetaObject.connectSlotsByName(TitleFromHistory)

    def retranslateUi(self, TitleFromHistory):
        pass
